# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='personpoked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='app1.User'),
        ),
        migrations.AlterField(
            model_name='poke',
            name='personpoking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poking', to='app1.User'),
        ),
    ]
